# Generated by Django 2.2.3 on 2019-07-22 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='author_quote',
        ),
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(default='author', max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='user_favourited',
            field=models.ManyToManyField(blank=True, related_name='user_favourited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quote',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='quote',
            name='user_liked',
            field=models.ManyToManyField(blank=True, related_name='user_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
