# Generated by Django 2.2.3 on 2019-07-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='check_favourited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='check_liked',
            field=models.BooleanField(default=False),
        ),
    ]
