# Generated by Django 2.2.3 on 2019-07-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorQuote',
        ),
    ]
